### ISSUE TITLE
Should this be setTransactionId instead?

### ISSUE THREAD

**Issue by Nemo144** [pointblankdev/apollo-plugin-sentry#1]
https://github.com/pointblankdev/apollo-plugin-sentry/blob/698bf2e2b809b4d2b340fa9dbda4338eaf78ecf2/src/index.ts#L50

**Comment by supercede** [comment]
It used to be setTransaction, but that's been deprecated in favour of setTransactionName. Thanks for bringing this up though

https://docs.sentry.io/platforms/node/enriching-events/transaction-name/
